import { StyleSheet } from "react-native";
import { ThemeContextType } from "./ThemeContext";

export const createGlobalStyles = (theme: ThemeContextType) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.colors.background,
    },
    header: {
      paddingVertical: 16,
      borderBottomWidth: 1,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      position: "relative",
      height: 200,
    },
    backButton: {
      position: "absolute",
      top: 50,
      left: 24,
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: "rgba(0, 0, 0, 0.5)",
      alignItems: "center",
      justifyContent: "center",
    },
    headerTitle: {
      fontSize: 18,
      fontWeight: "600",
      fontFamily: "Inter-SemiBold",
    },
    placeholder: {
      width: 40,
    },
    content: {
      flex: 1,
      paddingHorizontal: 12,
    },
    section: {
      backgroundColor: theme.colors.surface,
      paddingHorizontal: 24,
      paddingVertical: 20,
      marginBottom: 8,
    },
    sectionHeader: {
      fontSize: 12,
      fontWeight: "bold",
      letterSpacing: 1,
      paddingHorizontal: 24,
      paddingVertical: 12,
      fontFamily: "Inter-Bold",
    },
    settingsItem: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 24,
      paddingVertical: 16,
      borderBottomWidth: 1,
    },
    settingsItemLeft: {
      flexDirection: "row",
      alignItems: "center",
      flex: 1,
    },
    settingsItemText: {
      marginLeft: 16,
      flex: 1,
    },
    settingsItemTitle: {
      fontSize: 16,
      fontFamily: "Inter-Regular",
    },
    settingsItemSubtitle: {
      fontSize: 14,
      marginTop: 2,
      fontFamily: "Inter-Regular",
    },
    themeSelector: {
      flexDirection: "row",
      alignItems: "center",
    },
    themeButton: {
      width: 32,
      height: 32,
      borderRadius: 16,
      borderWidth: 1,
      alignItems: "center",
      justifyContent: "center",
      marginLeft: 8,
    },
    logoutButton: {
      marginTop: 32,
      marginHorizontal: 24,
      paddingVertical: 16,
      borderRadius: 12,
      alignItems: "center",
    },
    logoutText: {
      fontSize: 16,
      fontWeight: "600",
      fontFamily: "Inter-SemiBold",
    },
    bottomPadding: {
      height: 35,
    },
    largeBottomPadding: {
      height: 120,
    },
    //   ----------------------------------
    headerContent: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    greeting: {
      fontSize: 24,
      fontWeight: "bold",
      fontFamily: "Inter-Bold",
    },
    packageInfo: {
      fontSize: 14,
      marginTop: 4,
      fontFamily: "Inter-Regular",
    },
    profilePicture: {
      position: "absolute",
      bottom: -40,
      left: 24,
      width: 80,
      height: 80,
      borderRadius: 40,
      borderWidth: 4,
      borderColor: theme.colors.surface,
    },
    searchSection: {
      paddingHorizontal: 12,
      paddingVertical: 16,
    },
    searchBar: {
      borderRadius: 12,
      paddingHorizontal: 16,
      paddingVertical: 12,
      flexDirection: "row",
      alignItems: "center",
      shadowColor: "#000000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
      marginBottom: 16,
      fontSize: 16,
      fontFamily: "Inter-Regular",
      maxHeight: 200,
    },
    searchInput: {
      flex: 1,
      fontSize: 16,
      fontFamily: "Inter-Regular",
      maxHeight: 80,
    },
    micButton: {
      padding: 8,
    },
    tagsSection: {
      marginBottom: 24,
    },
    tagsSectionHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 12,
    },
    sectionTitle: {
      fontSize: 16,
      fontWeight: "600",
      fontFamily: "Inter-SemiBold",
      marginBottom: 12,
    },
    addTagButton: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 16,
    },
    addTagText: {
      fontSize: 14,
      marginLeft: 4,
      fontFamily: "Inter-Medium",
    },
    selectedTags: {
      flexDirection: "row",
      flexWrap: "wrap",
      marginBottom: 12,
      gap: 11,
    },
    selectedTag: {
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 16,
      flexDirection: "row",
      alignItems: "center",
      marginRight: 8,
      marginBottom: 8,
    },
    selectedTagText: {
      color: "#FFFFFF",
      fontSize: 14,
      marginRight: 4,
      fontFamily: "Inter-Medium",
    },
    categoryDropdown: {
      borderWidth: 1,
      borderRadius: 8,
      paddingHorizontal: 16,
      paddingVertical: 12,
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    dropdownText: {
      fontSize: 16,
      fontFamily: "Inter-Regular",
    },
    searchButton: {
      marginBottom: 12,
    },
    emptyState: {
      alignItems: "center",
      marginBottom: 12,
    },
    emptyStateImage: {
      width: 150,
      height: 150,
      marginBottom: 16,
    },
    emptyStateText: {
      fontSize: 18,
      textAlign: "center",
      fontFamily: "Inter-Medium",
      lineHeight: 24,
      paddingHorizontal: 32,
      marginBottom: 24,
    },
    quickActions: {
      flexDirection: "row",
      flexWrap: "wrap",
      justifyContent: "space-between",
      marginBottom: 100,
    },
    actionButton: {
      width: "48%",
      paddingVertical: 20,
      paddingHorizontal: 16,
      borderRadius: 12,
      alignItems: "center",
      marginBottom: 16,
      shadowColor: "#000000",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 2,
      elevation: 2,
    },
    actionButtonText: {
      fontSize: 14,
      marginTop: 8,
      textAlign: "center",
      fontFamily: "Inter-Medium",
    },
    fab: {
      position: "absolute",
      bottom: 24,
      right: 24,
      width: 56,
      height: 56,
      borderRadius: 28,
      alignItems: "center",
      justifyContent: "center",
      shadowColor: "#000000",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 8,
    },
    modalContainer: {
      flex: 1,
    },
    modalHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingHorizontal: 24,
      paddingVertical: 16,
      borderBottomWidth: 1,
    },
    modalTitle: {
      fontSize: 18,
      fontWeight: "600",
      fontFamily: "Inter-SemiBold",
    },
    customTagInput: {
      flexDirection: "row",
      paddingHorizontal: 24,
      paddingVertical: 16,
      marginBottom: 8,
    },
    tagInput: {
      flex: 1,
      borderWidth: 1,
      borderRadius: 8,
      paddingHorizontal: 12,
      paddingVertical: 8,
      fontSize: 16,
      marginRight: 12,
      fontFamily: "Inter-Regular",
    },
    addButton: {
      paddingHorizontal: 16,
      paddingVertical: 8,
      borderRadius: 8,
      justifyContent: "center",
    },
    addButtonText: {
      color: "#FFFFFF",
      fontSize: 16,
      fontWeight: "600",
      fontFamily: "Inter-SemiBold",
    },
    categoriesList: {
      paddingHorizontal: 24,
      paddingVertical: 16,
      gap: 11,
    },
    categoryTag: {
      borderWidth: 1,
      paddingHorizontal: 16,
      paddingVertical: 12,
      borderRadius: 20,
      margin: 4,
      flex: 1,
      alignItems: "center",
    },
    categoryTagText: {
      fontSize: 14,
      fontFamily: "Inter-Medium",
    },
    //   ----------------------------------
    listContainer: {
      paddingHorizontal: 24,
      paddingVertical: 16,
    },
    sessionCard: {
      backgroundColor: theme.colors.surface,
      borderRadius: 12,
      padding: 16,
      marginBottom: 16,
      shadowColor: "#000000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
      borderBottomWidth: 1,

      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingVertical: 12,
    },
    sessionHeader: {
      flexDirection: "row",
      alignItems: "flex-start",
      marginBottom: 12,
    },
    sessionInfo: {
      flex: 1,
      marginLeft: 12,
    },
    statusBadge: {
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 12,
    },
    statusText: {
      fontSize: 12,
      color: theme.colors.textSecondary,
      marginRight: "auto",
      fontFamily: "Inter-Medium",
      marginLeft: 8,
    },
    sessionContent: {
      marginBottom: 12,
    },
    problemText: {
      fontSize: 14,
      color: theme.colors.textSecondary,
      marginBottom: 12,
      lineHeight: 20,
      fontFamily: "Inter-Regular",
    },
    tagsContainer: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
      marginBottom: 16,
    },
    ratingSection: {
      borderTopWidth: 1,
      borderTopColor: theme.colors.border,
      paddingTop: 12,
    },
    ratingStars: {
      flexDirection: "row",
      marginBottom: 8,
    },
    reviewText: {
      fontSize: 14,
      color: theme.colors.textSecondary,
      fontStyle: "italic",
      lineHeight: 20,
      fontFamily: "Inter-Regular",
    },
    sessionActions: {
      flexDirection: "row",
      justifyContent: "space-between",
      borderTopWidth: 1,
      borderTopColor: theme.colors.border,
      paddingTop: 12,
    },
    rescheduleButton: {
      flex: 1,
      paddingVertical: 8,
      paddingHorizontal: 16,
      borderWidth: 1,
      borderColor: theme.colors.border,
      borderRadius: 8,
      alignItems: "center",
      marginRight: 8,
    },
    joinButton: {
      flex: 1,
      paddingVertical: 8,
      paddingHorizontal: 16,
      backgroundColor: theme.colors.primary,
      borderRadius: 8,
      alignItems: "center",
      marginLeft: 8,
    },
    emptyStateTitle: {
      marginTop: 16,
      marginBottom: 8,
    },
    // ----------------
    profileSection: {
      backgroundColor: theme.colors.surface,
      paddingHorizontal: 24,
      paddingVertical: 32,
      marginBottom: 16,
    },
    profileImageContainer: {
      alignItems: "center",
      marginBottom: 24,
      position: "relative",
    },
    changePhotoButton: {
      position: "absolute",
      bottom: 0,
      right: "35%",
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: theme.colors.primary,
      alignItems: "center",
      justifyContent: "center",
    },
    profileInfo: {
      alignItems: "flex-start",
      backgroundColor: theme.colors.surface,
      paddingHorizontal: 24,
      paddingTop: 50,
      paddingBottom: 24,
      marginBottom: 8,
    },
    userStats: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: theme.colors.background,
      borderRadius: 12,
      paddingVertical: 16,
      paddingHorizontal: 24,
      width: "100%",
    },
    statItem: {
      flex: 1,
      alignItems: "center",
    },
    statDivider: {
      width: 1,
      height: 32,
      backgroundColor: theme.colors.border,
      marginHorizontal: 16,
    },
    editActions: {
      flexDirection: "row",
      marginTop: 24,
      gap: 12,
    },
    cancelButton: {
      flex: 1,
      backgroundColor: theme.colors.border,
    },
    saveButton: {
      flex: 1,
    },
    ratingsSection: {
      backgroundColor: theme.colors.surface,
      paddingHorizontal: 24,
      paddingVertical: 20,
      marginBottom: 16,
    },
    ratingCard: {
      backgroundColor: theme.colors.background,
      borderRadius: 12,
      padding: 16,
      marginBottom: 12,
    },
    ratingHeader: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: 12,
    },
    coachInfo: {
      flex: 1,
      marginLeft: 12,
    },
    emptyRatings: {
      alignItems: "center",
      paddingVertical: 32,
    },
    accountSection: {
      backgroundColor: theme.colors.surface,
      paddingHorizontal: 24,
      paddingVertical: 20,
      marginBottom: 16,
    },
    infoCard: {
      backgroundColor: theme.colors.background,
      borderRadius: 12,
      padding: 16,
    },
    infoRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingVertical: 12,
      borderBottomWidth: 1,
      borderBottomColor: theme.colors.border,
    },
    averageRating: {
      flexDirection: "row",
      alignItems: "center",
    },
    stars: {
      flexDirection: "row",
      marginRight: 8,
    },

    //   ----------------------------------
    safeArea: {
      flex: 1,
    },
    keyboardView: {
      flex: 1,
    },
    card: {
      borderRadius: 12,
      padding: 32,
      shadowColor: "#000000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 10,
      elevation: 5,
    },
    logoContainer: {
      alignItems: "center",
      marginBottom: 24,
    },
    logo: {
      fontSize: 32,
      fontWeight: "bold",
      fontFamily: "Inter-Bold",
    },
    illustration: {
      width: "100%",
      height: 150,
      marginBottom: 24,
    },
    headline: {
      fontSize: 24,
      fontWeight: "bold",
      textAlign: "center",
      marginBottom: 8,
      fontFamily: "Inter-Bold",
    },
    subheading: {
      fontSize: 16,
      textAlign: "center",
      marginBottom: 32,
      lineHeight: 24,
      fontFamily: "Inter-Regular",
    },
    form: {
      marginBottom: 24,
    },
    input: {
      borderWidth: 1,
      borderRadius: 12,
      paddingHorizontal: 16,
      paddingVertical: 12,
      fontSize: 16,
      marginBottom: 16,
      fontFamily: "Inter-Regular",
    },
    primaryButton: {
      marginBottom: 16,
    },
    secondaryButton: {
      marginTop: 8,
    },
    footer: {
      fontSize: 12,
      textAlign: "center",
      lineHeight: 18,
      fontFamily: "Inter-Regular",
    },
    // ---------------------
    coachCard: {
      backgroundColor: theme.colors.surface,
      borderRadius: 12,
      padding: 16,
      marginBottom: 16,
      shadowColor: "#000000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    cardContent: {
      flexDirection: "row",
      marginBottom: 12,
    },
    availabilityContainer: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: 8,
    },
    cardActions: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      borderTopWidth: 1,
      borderTopColor: theme.colors.border,
      paddingTop: 12,
    },
    favoriteButton: {
      width: 44,
      height: 44,
      borderRadius: 24,
      backgroundColor: theme.colors.accent + "20",
      alignItems: "center",
      justifyContent: "center",
      marginRight: 16,
    },
    connectButton: {
      flex: 1,
      backgroundColor: theme.colors.primary,
      paddingHorizontal: 24,
      paddingVertical: 10,
      borderRadius: 20,
    },
    // ------------------
    filterRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    filterButton: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 16,
    },
    filterText: {
      fontSize: 14,
      marginLeft: 4,
      fontFamily: "Inter-Medium",
    },
    sortButton: {
      flexDirection: "row",
      alignItems: "center",
    },
    sortText: {
      fontSize: 14,
      marginRight: 4,
      fontFamily: "Inter-Medium",
    },
    // -----------------------
    coverPhoto: {
      width: "100%",
      height: 200,
    },
    nameSection: {
      marginBottom: 12,
    },
    experience: {
      fontSize: 14,
      color: theme.colors.primary,
      marginTop: 4,
      fontFamily: "Inter-Medium",
    },
    availabilitySection: {
      flexDirection: "row",
      alignItems: "center",
    },
    hourlyRate: {
      fontSize: 16,
      fontWeight: "600",
      color: theme.colors.text,
      fontFamily: "Inter-SemiBold",
    },
    bio: {
      fontSize: 16,
      color: theme.colors.textSecondary,
      lineHeight: 24,
      fontFamily: "Inter-Regular",
    },
    specialtiesContainer: {
      flexDirection: "row",
      flexWrap: "wrap",
    },
    specialtyTag: {
      backgroundColor: theme.colors.primary + "20",
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 16,
      marginRight: 8,
      marginBottom: 8,
    },
    specialtyText: {
      fontSize: 14,
      color: theme.colors.primary,
      fontFamily: "Inter-Medium",
    },
    reviewCard: {
      backgroundColor: theme.colors.background,
      padding: 16,
      borderRadius: 12,
      marginBottom: 12,
    },
    reviewHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 8,
    },
    reviewStars: {
      flexDirection: "row",
    },
    seeAllReviews: {
      alignItems: "center",
    },
    seeAllText: {
      fontSize: 14,
      color: theme.colors.primary,
      fontFamily: "Inter-Medium",
    },
    stickyActionBar: {
      position: "absolute",
      bottom: 0,
      left: 0,
      right: 0,
      backgroundColor: theme.colors.surface,
      paddingHorizontal: 24,
      paddingVertical: 16,
      flexDirection: "row",
      alignItems: "center",
      borderTopWidth: 1,
      borderTopColor: theme.colors.border,
      shadowColor: "#000000",
      shadowOffset: { width: 0, height: -2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 5,
    },
    // ---------------------------

    statusSection: {
      borderRadius: 12,
      padding: 20,
      marginTop: 16,
      marginBottom: 16,
    },
    statusHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 8,
    },
    statsContainer: {
      flexDirection: "row",
      justifyContent: "space-between",
      marginBottom: 24,
    },
    statCard: {
      borderRadius: 12,
      padding: 16,
      alignItems: "center",
      flex: 1,
      marginHorizontal: 4,
      shadowColor: "#000000",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 2,
      elevation: 2,
    },
    statValue: {
      marginTop: 8,
      marginBottom: 4,
    },
    progressSection: {
      borderRadius: 12,
      padding: 20,
      marginBottom: 24,
    },
    progressBar: {
      height: 8,
      borderRadius: 4,
      marginBottom: 8,
    },
    progressFill: {
      height: "100%",
      borderRadius: 4,
    },
    progressText: {
      marginBottom: 4,
    },
    sessionsSection: {
      borderRadius: 12,
      padding: 20,
      marginBottom: 24,
    },
    clientName: {
      marginBottom: 2,
    },
    sessionTime: {
      marginTop: 2,
    },
    startCallButton: {
      paddingHorizontal: 12,
      paddingVertical: 6,
    },
    completedBadge: {
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 16,
    },
    actionCard: {
      borderRadius: 12,
      padding: 20,
      width: "48%",
      alignItems: "center",
      marginBottom: 16,
      shadowColor: "#000000",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 2,
      elevation: 2,
    },
    actionTitle: {
      marginTop: 12,
      marginBottom: 4,
    },
  });
